from django.urls import path

from .views import *

urlpatterns = [
    path('', HomeView.as_view(), name='admin_home'),
    path('profile/r/<int:pk>/', ReaderProfileView.as_view(), name='a_reader_profile'),
    path('profile/r/update/<int:pk>/', ReaderUpdateView.as_view(), name='a_reader_update'),
    path('profile/r/delete/<int:pk>/', ReaderDeleteView.as_view(), name='a_reader_delete'),
    path('profile/w/<int:pk>/', WriterProfileView.as_view(), name='a_writer_profile'),
    path('profile/w/update/<int:pk>/', WriterUpdateView.as_view(), name='a_writer_update'),
    path('profile/w/delete/<int:pk>/', WriterDeleteView.as_view(), name='a_writer_delete'),
    path('profile/a/<int:pk>/', AdminProfileView.as_view(), name='a_admin_profile'),
    path('profile/a/update/', AdminUpdateView.as_view(), name='a_admin_update'),
    path('password/change/', ChangePasswordView.as_view(), name='admin_change_password'),
    path('manage/user/', ManageUserView.as_view(), name='a_manage_user'),
    path('create/user/', UserCreateView.as_view(), name='a_user_create'),
    path('manage/article/', ManageArticleView.as_view(), name='a_manage_article'),
    path('create/article/', ArticleCreateView.as_view(), name='a_article_create'),
    path('article/detail/<int:pk>/', ArticleDetailView.as_view(), name='a_article_detail'),
    path('article/like/<int:pk>/', ArticleLikeView.as_view(), name='a_article_like'),
    path('article/liker/<int:pk>/', ArticleLikerView.as_view(), name='a_article_liker'),
    path('article/update/<int:pk>/', ArticleUpdateView.as_view(), name='a_article_update'),
    path('article/delete/<int:pk>/', ArticleDeleteView.as_view(), name='a_article_delete'),
    path('comment/update/<int:pk>/', CommentUpdateView.as_view(), name='a_comment_update'),
    path('comment/reply/<int:pk>/', CommentReplyView.as_view(), name='a_reply_comment'),
    path('comment/delete/<int:pk>/', CommentDeleteView.as_view(), name='a_comment_delete'),
    path('manage/category/', ManageCategoryView.as_view(), name='a_manage_category'),
    path('create/category/', CategoryCreateView.as_view(), name='a_category_create'),
    path('articles/<category>/', ArticleCategoryList.as_view(), name='a_article_category_list'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='a_category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='a_category_delete'),
    path('manage/contact/', ManageContactView.as_view(), name='a_manage_contact'),
    path('create/contact/', ContactCreateView.as_view(), name='a_contact_create'),
    path('contact/update/<int:pk>/', ContactUpdateView.as_view(), name='a_contact_update'),
    path('manage/team/', ManageTeamView.as_view(), name='a_manage_team'),
    path('create/team/', TeamCreateView.as_view(), name='a_team_create'),
    path('team/detail/<int:pk>/', TeamDetailView.as_view(), name='a_team_detail'),
    path('team/update/<int:pk>/', TeamUpdateView.as_view(), name='a_team_update'),
    path('team/delete/<int:pk>/', TeamDeleteView.as_view(), name='a_team_delete'),
    path('manage/log/', ManageLogView.as_view(), name='a_manage_log'),
]
